import type { Metadata } from "next";
import Link from "next/link";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { SiteFooter } from "@/components/site-footer";

export const metadata: Metadata = { title: "Divulgación de afiliados", description: "Cómo funcionan los enlaces de afiliado y cómo preservamos la independencia editorial de NextFaro.", alternates: { canonical: "/divulgacion-afiliados" } };

export default function AffiliateDisclosurePage() {
  return <main className="min-h-screen bg-[#f6efe2] text-[#17130d]"><article className="px-5 py-10 sm:px-8 lg:px-10"><div className="mx-auto max-w-3xl"><Breadcrumbs items={[{ label: "Inicio", href: "/" }, { label: "Divulgación de afiliados", href: "/divulgacion-afiliados" }]} /><h1 className="mt-8 font-serif text-4xl font-semibold sm:text-5xl">Divulgación de afiliados</h1><div className="mt-7 space-y-6 text-lg leading-9 text-[#3d3427]"><p>Algunos enlaces de compra de NextFaro son enlaces de afiliado. Si visitas una tienda mediante uno de esos enlaces y realizas una compra elegible, NextFaro puede recibir una comisión sin costo adicional para ti.</p><h2 className="font-serif text-3xl font-semibold">La comisión no decide qué recomendamos</h2><p>La existencia o el importe potencial de una comisión no determina la inclusión de un libro, su categoría ni la opinión editorial. Una ficha puede señalar límites, falta de evidencia o razones para elegir otra obra aunque contenga un enlace de compra.</p><h2 className="font-serif text-3xl font-semibold">Precios, disponibilidad y condiciones externas</h2><p>NextFaro no controla el precio final, el inventario, la edición, el envío, la devolución ni las políticas de la tienda. Comprueba esos datos en el sitio externo antes de comprar. La información editorial de nuestras guías es independiente de las condiciones comerciales.</p><h2 className="font-serif text-3xl font-semibold">Cómo identificamos estos enlaces</h2><p>Antes de cada botón de compra mostramos un aviso visible. Los enlaces también incluyen la relación técnica correspondiente para indicar que pueden ser patrocinados. Puedes leer todas las guías sin comprar ni utilizar esos enlaces.</p><p>Si detectas un enlace incorrecto o una relación comercial que no esté explicada con claridad, escríbenos desde la página de <Link className="font-semibold text-[#8a5d12] underline" href="/contacto">contacto</Link>.</p></div></div></article><SiteFooter /></main>;
}
